### Post new step
POST http://localhost:8000/stories/{{chapterId}}/step
Content-Type: application/json

{
    "stepNumber": 1,
    "stepWidth": 800,
    "visible": true,
    "title": "First Step",
    "html": "<p>Welcome to the story!</p>",
    "centerCoordinate": [52.520008, 13.404954],
    "zoomLevel": 12,
    "interactionAddons": ["tooltip", "popup"],
    "is3D": true,
    "backgroundMapId": "map-1234",
    "navigation3D": {
        "cameraPosition": [0.0],
        "heading": 0.0,
        "pitch": 0.0
    }
}
###
