// This file was auto-generated by prisma-generator-typescript-interfaces

export interface Layer {
  id: number;
  transparency: number;
  selectionIDX: number;
}

export interface Chapter {
  id: number;
  sequence: number;
  name: string;
  story?: Story;
  storyId: number;
  StoryStep?: StoryStep[];
}

export interface Datasource {
  id: number;
  step?: StoryStep;
  stepId: number;
}

export interface ThreeDFiles {
  file?: File;
  step?: StoryStep;
  fileId: number;
  storyStepId: number;
}

export interface wmsLayer {
  id: number;
  url: string;
  selectedLayers: string[];
  step?: StoryStep;
  stepId: number;
}

export interface Orientation {
  id: number;
  heading: number;
  roll: number;
  pitch: number;
  SelectedModelId?: SelectedModelId[];
}

export interface Position {
  id: number;
  x: number;
  y: number;
  z: number;
  SelectedModelId?: SelectedModelId[];
}

export interface SelectedModelId {
  id: number;
  modelId: string;
  orientation?: Orientation;
  scale: number;
  orientationId: number;
  Position?: Position | null;
  positionId: number | null;
}

export type GeoJSONAsset = {
  id: string;
  title: string;
  geoJson: JsonValue;
};

export type InformationLayer = {
  id: string;
  attributes: JsonValue;
}

export interface StoryStep {
  id: number;
  stepNumber: number;
  chapter?: Chapter;
  chapterId: number;
  stepWidth: number;
  visible: boolean;
  title: string;
  html: string;
  centerCoordinate: number[];
  zoomLevel: number;
  interactionAddons: string[];
  is3D: boolean;
  navigation3D: JsonValue;
  backgroundMapId: string;
  datasources?: Datasource[];
  wmsLayers?: wmsLayer[];
  ThreeDFiles?: ThreeDFiles[];
  informationLayers?: InformationLayer[];
  geoJsonAssets: GeoJSONAsset[];
}

export interface File {
  id: number;
  bucket: string;
  fileContext: string | null;
  filename: string;
  key: string;
  provider: string;
  providerMetaData: JsonValue;
  fileSize: bigint | null;
  mimetype: string;
  encoding: string;
  Story?: Story[];
  ThreeDFiles?: ThreeDFiles[];
  owner: string | null;
}

export interface Story {
  id: number;
  title: string;
  description: string;
  author: string;
  storyInterval: number;
  titleImage?: File | null;
  titleImageId: number | null;
  displayType: string | null;
  chapters?: Chapter[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  owner: string;
  private: boolean;
  sharedWith: string[];
  featured: boolean;
  views: number;
  isDraft: boolean;
}

export interface KeycloakSetup {
  id: number;
  authUri: string;
  tokenUri: string;
  clientId: string;
  scope: string;
  redirectUri: string;
}

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
