### Get Stories
GET {{baseUri}}/stories
Content-Type: application/json
###


### Get specific story
GET {{baseUri}}/stories/26
Content-Type: application/json
###


### Play specific story
POST {{baseUri}}/stories/26/play
Content-Type: application/json
###
